# Generated by Django 5.2.4 on 2025-09-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_question_answer_remove_quiz_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video_url',
            field=models.URLField(default='http://test.com'),
            preserve_default=False,
        ),
    ]
